name: workflow run cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '05 * * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
